apiVersion: v1
kind: Service

metadata:
  name: banking-monitor-service

spec:
  selector:
    app: banking-monitor

  ports:
    - protocol: TCP
      port: 80
      targetPort: 5000

  type: NodePort